plugins:
    - jekyll-postcss
    - jekyll-purgecss

exclude:
    - .gitignore
    - README.md
    - node_modules
    - Gemfile
    - Gemfile.lock
    - package.json
    - package-lock.json
    - postcss.config.js
    - purgecss.config.js
    - tailwind.config.js

collections:
    jobs:
        output: false
